<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
    <AssemblyName>4u4free.PlaytimeIdler</AssemblyName>
    <RootNamespace>FourUFourFree.PlaytimeIdler</RootNamespace>
    <Version>0.5.2</Version>
    <AssemblyVersion>0.5.2.0</AssemblyVersion>
    <FileVersion>0.5.2.0</FileVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <PathMap>$(MSBuildProjectDirectory)=.</PathMap>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\third_party\steam-achievement-manager\</OutputPath>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SAM.API">
      <HintPath>..\..\third_party\steam-achievement-manager\SAM.API.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
