// LumaCore — Steam client hook layer for SteaMidra.
// Copyright (c) 2025-2026 Midrag (https://github.com/Midrags).
// Distributed under the GNU General Public License v3 or later.
// See <https://www.gnu.org/licenses/> for the full license text.

#pragma once

// Logging for LumaCore. Backed by spdlog, active only in Debug builds.
//
// CMake defines LUMACORE_LOGGING_ENABLED for Debug but not for Release.
// In Release builds every LOG_* macro expands to nothing, so the logging code
// is fully stripped out and adds zero overhead to the shipped DLL.
// In Debug builds, logs are written to <Steam>\lumacore\main.log (and per-module
// files for each hook module registered in ModuleLog.h).
//
// Main logger macros (all modules):
//   LOG_INFO("loaded {} bytes", n);
//   LOG_WARN("pattern missed for {}", name);
//   LOG_ERROR("CopyFileA failed: err={}", GetLastError());
//   LOG_DEBUG("hook attempt {}/{}", i, max);
//
// Per-module loggers are generated from ModuleLog.h using the LC_MOD X-macro.
// Each module gets its own log file and its own set of LOG_<MODULE>_* macros,
// e.g. LOG_IPCCH_INFO, LOG_MANIFESTCH_WARN, LOG_DECRYPTIONKEYCH_ERROR.

#ifdef LUMACORE_LOGGING_ENABLED

#ifndef SPDLOG_ACTIVE_LEVEL
    #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#endif

#include <spdlog/spdlog.h>
#include <spdlog/fmt/bin_to_hex.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <windows.h>
#include <memory>

namespace Logger {
    void Init(HMODULE selfModule);
    void InitModules();

    inline std::shared_ptr<spdlog::logger> Main;

    // Per-module loggers declared via LC_MOD entries in ModuleLog.h
    #define LC_MOD(v, f) inline std::shared_ptr<spdlog::logger> v;
    #include "ModuleLog.h"
    #undef LC_MOD
}

// ── General-purpose (main.log) ──────────────────────────────────────
#define LOG_TRACE(...) SPDLOG_LOGGER_TRACE(Logger::Main, __VA_ARGS__)
#define LOG_DEBUG(...) SPDLOG_LOGGER_DEBUG(Logger::Main, __VA_ARGS__)
#define LOG_INFO(...)  SPDLOG_LOGGER_INFO(Logger::Main, __VA_ARGS__)
#define LOG_WARN(...)  SPDLOG_LOGGER_WARN(Logger::Main, __VA_ARGS__)
#define LOG_ERROR(...) SPDLOG_LOGGER_ERROR(Logger::Main, __VA_ARGS__)

#else  // LUMACORE_LOGGING_ENABLED

#include <windows.h>

namespace Logger {
    inline void Init(HMODULE) {}
    inline void InitModules() {}
}

#define LOG_TRACE(...)  ((void)0)
#define LOG_DEBUG(...)  ((void)0)
#define LOG_INFO(...)   ((void)0)
#define LOG_WARN(...)   ((void)0)
#define LOG_ERROR(...)  ((void)0)

#endif  // LUMACORE_LOGGING_ENABLED

// Per-module LOG_<MOD>_* macros generated by cmake/LogMacros.cmake.
#include "lc_log_macros.h"

// Back-compat aliases for files pinned byte-identical by the B-preservation
// suite (LuaLoader.cpp via requirement 3.43). The X-macro identifiers were
// renamed to carry a `Ch` suffix so they no longer collide with shared channel
// tokens, and these aliases keep the pre-rename callsite spellings working
// without touching the pinned files.
#define LOG_PACKAGE_TRACE(...) LOG_PKGCH_TRACE(__VA_ARGS__)
#define LOG_PACKAGE_DEBUG(...) LOG_PKGCH_DEBUG(__VA_ARGS__)
#define LOG_PACKAGE_INFO(...)  LOG_PKGCH_INFO(__VA_ARGS__)
#define LOG_PACKAGE_WARN(...)  LOG_PKGCH_WARN(__VA_ARGS__)
#define LOG_PACKAGE_ERROR(...) LOG_PKGCH_ERROR(__VA_ARGS__)

// 6.2.4 hotfix: more back-compat aliases. The PacketRouter.cpp restore
// from backup brought in pre-rename macro names everywhere; rather than
// rewrite every callsite in the restored file, alias the old names to
// the suffix-Ch ones the rest of the tree uses.
#define LOG_ACHIEVEMENT_TRACE(...) LOG_ACHIEVEMENTCH_TRACE(__VA_ARGS__)
#define LOG_ACHIEVEMENT_DEBUG(...) LOG_ACHIEVEMENTCH_DEBUG(__VA_ARGS__)
#define LOG_ACHIEVEMENT_INFO(...)  LOG_ACHIEVEMENTCH_INFO(__VA_ARGS__)
#define LOG_ACHIEVEMENT_WARN(...)  LOG_ACHIEVEMENTCH_WARN(__VA_ARGS__)
#define LOG_ACHIEVEMENT_ERROR(...) LOG_ACHIEVEMENTCH_ERROR(__VA_ARGS__)

#define LOG_NETPACKET_TRACE(...) LOG_WIRECH_TRACE(__VA_ARGS__)
#define LOG_NETPACKET_DEBUG(...) LOG_WIRECH_DEBUG(__VA_ARGS__)
#define LOG_NETPACKET_INFO(...)  LOG_WIRECH_INFO(__VA_ARGS__)
#define LOG_NETPACKET_WARN(...)  LOG_WIRECH_WARN(__VA_ARGS__)
#define LOG_NETPACKET_ERROR(...) LOG_WIRECH_ERROR(__VA_ARGS__)

#define LOG_ONLINEFIX_TRACE(...) LOG_ONLINEFIXCH_TRACE(__VA_ARGS__)
#define LOG_ONLINEFIX_DEBUG(...) LOG_ONLINEFIXCH_DEBUG(__VA_ARGS__)
#define LOG_ONLINEFIX_INFO(...)  LOG_ONLINEFIXCH_INFO(__VA_ARGS__)
#define LOG_ONLINEFIX_WARN(...)  LOG_ONLINEFIXCH_WARN(__VA_ARGS__)
#define LOG_ONLINEFIX_ERROR(...) LOG_ONLINEFIXCH_ERROR(__VA_ARGS__)

#define LOG_PICS_TRACE(...) LOG_PICSCH_TRACE(__VA_ARGS__)
#define LOG_PICS_DEBUG(...) LOG_PICSCH_DEBUG(__VA_ARGS__)
#define LOG_PICS_INFO(...)  LOG_PICSCH_INFO(__VA_ARGS__)
#define LOG_PICS_WARN(...)  LOG_PICSCH_WARN(__VA_ARGS__)
#define LOG_PICS_ERROR(...) LOG_PICSCH_ERROR(__VA_ARGS__)

#define LOG_MISC_TRACE(...) LOG_MISCCH_TRACE(__VA_ARGS__)
#define LOG_MISC_DEBUG(...) LOG_MISCCH_DEBUG(__VA_ARGS__)
#define LOG_MISC_INFO(...)  LOG_MISCCH_INFO(__VA_ARGS__)
#define LOG_MISC_WARN(...)  LOG_MISCCH_WARN(__VA_ARGS__)
#define LOG_MISC_ERROR(...) LOG_MISCCH_ERROR(__VA_ARGS__)

// New per-module aliases for the retroactive-divergence channels.
#define LOG_MANBND_TRACE(...) LOG_MANBNDCH_TRACE(__VA_ARGS__)
#define LOG_MANBND_DEBUG(...) LOG_MANBNDCH_DEBUG(__VA_ARGS__)
#define LOG_MANBND_INFO(...)  LOG_MANBNDCH_INFO(__VA_ARGS__)
#define LOG_MANBND_WARN(...)  LOG_MANBNDCH_WARN(__VA_ARGS__)
#define LOG_MANBND_ERROR(...) LOG_MANBNDCH_ERROR(__VA_ARGS__)

#define LOG_IPCRTR_TRACE(...) LOG_IPCRTRCH_TRACE(__VA_ARGS__)
#define LOG_IPCRTR_DEBUG(...) LOG_IPCRTRCH_DEBUG(__VA_ARGS__)
#define LOG_IPCRTR_INFO(...)  LOG_IPCRTRCH_INFO(__VA_ARGS__)
#define LOG_IPCRTR_WARN(...)  LOG_IPCRTRCH_WARN(__VA_ARGS__)
#define LOG_IPCRTR_ERROR(...) LOG_IPCRTRCH_ERROR(__VA_ARGS__)

#define LOG_USRCMD_TRACE(...) LOG_USRCMDCH_TRACE(__VA_ARGS__)
#define LOG_USRCMD_DEBUG(...) LOG_USRCMDCH_DEBUG(__VA_ARGS__)
#define LOG_USRCMD_INFO(...)  LOG_USRCMDCH_INFO(__VA_ARGS__)
#define LOG_USRCMD_WARN(...)  LOG_USRCMDCH_WARN(__VA_ARGS__)
#define LOG_USRCMD_ERROR(...) LOG_USRCMDCH_ERROR(__VA_ARGS__)

#define LOG_PKTRT_TRACE(...) LOG_PKTRTCH_TRACE(__VA_ARGS__)
#define LOG_PKTRT_DEBUG(...) LOG_PKTRTCH_DEBUG(__VA_ARGS__)
#define LOG_PKTRT_INFO(...)  LOG_PKTRTCH_INFO(__VA_ARGS__)
#define LOG_PKTRT_WARN(...)  LOG_PKTRTCH_WARN(__VA_ARGS__)
#define LOG_PKTRT_ERROR(...) LOG_PKTRTCH_ERROR(__VA_ARGS__)

#define LOG_COREIN_TRACE(...) LOG_COREINCH_TRACE(__VA_ARGS__)
#define LOG_COREIN_DEBUG(...) LOG_COREINCH_DEBUG(__VA_ARGS__)
#define LOG_COREIN_INFO(...)  LOG_COREINCH_INFO(__VA_ARGS__)
#define LOG_COREIN_WARN(...)  LOG_COREINCH_WARN(__VA_ARGS__)
#define LOG_COREIN_ERROR(...) LOG_COREINCH_ERROR(__VA_ARGS__)

// New aliases for the retro-fitted IPC dispatch and Denuvo auth channels.
#define LOG_IPC_TRACE(...) LOG_IPCCH_TRACE(__VA_ARGS__)
#define LOG_IPC_DEBUG(...) LOG_IPCCH_DEBUG(__VA_ARGS__)
#define LOG_IPC_INFO(...)  LOG_IPCCH_INFO(__VA_ARGS__)
#define LOG_IPC_WARN(...)  LOG_IPCCH_WARN(__VA_ARGS__)
#define LOG_IPC_ERROR(...) LOG_IPCCH_ERROR(__VA_ARGS__)

#define LOG_AUTH_TRACE(...) LOG_AUTHCH_TRACE(__VA_ARGS__)
#define LOG_AUTH_DEBUG(...) LOG_AUTHCH_DEBUG(__VA_ARGS__)
#define LOG_AUTH_INFO(...)  LOG_AUTHCH_INFO(__VA_ARGS__)
#define LOG_AUTH_WARN(...)  LOG_AUTHCH_WARN(__VA_ARGS__)
#define LOG_AUTH_ERROR(...) LOG_AUTHCH_ERROR(__VA_ARGS__)

// LuaLoader logs already route through the package channel via the
// LOG_PACKAGE_* aliases above. The LOG_LUA_* group exists so the Lua
// uint64 parse guard at LuaBindings.cpp / LuaQuery.cpp can call out the
// binding context without inventing a new channel and forcing a CMake
// regen of the per-module macro header.
#define LOG_LUA_TRACE(...) LOG_PKGCH_TRACE(__VA_ARGS__)
#define LOG_LUA_DEBUG(...) LOG_PKGCH_DEBUG(__VA_ARGS__)
#define LOG_LUA_INFO(...)  LOG_PKGCH_INFO(__VA_ARGS__)
#define LOG_LUA_WARN(...)  LOG_PKGCH_WARN(__VA_ARGS__)
#define LOG_LUA_ERROR(...) LOG_PKGCH_ERROR(__VA_ARGS__)
